apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-k8s-conf
  namespace: {{ .Values.nameSpace }}
data:
  tyk_k8s.yaml: |-
    Server:
      addr: ":443"
      certFile: "/etc/tyk-k8s/certs/cert.pem"
      keyFile: "/etc/tyk-k8s/certs/key.pem"
    Tyk:
      url: "http://dashboard-svc-{{ include "tyk-pro.fullname" . }}.{{ .Values.nameSpace }}:{{ .Values.dash.service.port }}"
      secret: "set-by-env"
      org: "set-by-env"
    Injector:
      createRoutes: true
      containers:
        - name: tyk-mesh
          image: lonelycode/tyk-micro:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIGOCLUSTER_SHARDCOUNT
              value: "{{ .Values.redis.shardCount }}"
            - name: TYK_GW_STORAGE_HOSTS
              value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
            - name: TYK_GW_STORAGE_USESSL
              value: "false"
            - name: TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING
              value: "http://dashboard-svc-{{ include "tyk-pro.fullname" . }}.{{ .Values.nameSpace }}:{{ .Values.dash.service.port }}"
            - name: TYK_GW_POLICIES_POLICYCONNECTIONSTRING
              value: "http://dashboard-svc-{{ include "tyk-pro.fullname" . }}.{{ .Values.nameSpace }}:{{ .Values.dash.service.port }}"
            - name: TYK_GW_SECRET
              value: "{{ .Values.secrets.APISecret }}"
            - name: TYK_GW_NODESECRET
              value: "{{ .Values.secrets.APISecret }}"
            - name: TYK_GW_ENABLECUSTOMDOMAINS
              value: "true"
          command: ["/opt/tyk-gateway/tyk", "--conf=/opt/tyk-gateway/tyk.conf"]
          workingDir: /opt/tyk-gateway
          ports:
            - containerPort: 8080
      initContainers:
        - image: centos
          imagePullPolicy: Always
          name: run-iptables
          securityContext:
            privileged: true
          command:
            - "sh"
            - "-c"
            - 'yum -y install iptables; iptables -t nat -A OUTPUT -p tcp --dport 80 -j DNAT --to-destination 127.0.0.1:8080; iptables -t nat -A OUTPUT -p tcp --dport 6767 -j DNAT --to-destination 127.0.0.1:80'
