apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pump-{{ include "tyk-pro.fullname" . }}
  labels:
    app: pump-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pump.replicaCount }}
  tolerations:
{{ toYaml .Values.pump.tolerations | indent 4 }}
  selector:
    matchLabels:
      app: pump-{{ include "tyk-pro.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pump-{{ include "tyk-pro.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
{{ toYaml .Values.pump.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.pump.affinity | indent 8 }}
      containers:
      - name: pump-{{ .Chart.Name }}
        image: "{{ .Values.pump.image.repository }}:{{ .Values.pump.image.tag }}"
        imagePullPolicy: {{ .Values.pump.image.pullPolicy }}
        workingDir: "/opt/tyk-pump"
        env:
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "{{ .Values.redis.shardCount }}"
          - name: PMP_MONGO_MONGOURL
            value: {{ .Values.mongo.mongoURL | quote }}
          - name: PMP_MONGO_MONGOUSESSL
            value: "{{ .Values.mongo.useSSL }}"
          - name: PMP_MONGOAGG_MONGOURL
            value:  {{ .Values.mongo.mongoURL | quote }}
          - name: PMP_MONGOAGG_MONGOUSESSL
            value:  "{{ .Values.mongo.useSSL }}"
          - name: TYK_PMP_REDIS_HOSTS
            value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
          - name: TYK_PMP_REDIS_PASSWORD
            value: "{{ .Values.redis.pass }}"
          - name: TYK_PMP_REDIS_REDISUSESSL
            value: "{{ .Values.redis.useSSL }}"
        command: ["/opt/tyk-pump/tyk-pump", "-c", "/etc/tyk-pump/pump.conf"]
        volumeMounts:
          - name: tyk-pump-conf
            mountPath: /etc/tyk-pump
        resources:
{{ toYaml .Values.pump.resources | indent 12 }}
      volumes:
        - name: tyk-pump-conf
          configMap:
            name: tyk-pump-conf
            items:
              - key: pump.conf
                path: pump.conf
