{{- if .Values.dash.ingress.enabled -}}
{{- $fullName := include "tyk-pro.fullname" . -}}
{{- $ingressPath := .Values.dash.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dash-ing-{{ $fullName }}
  labels:
    app: dash-ing-{{ $fullName }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.dash.ingress.annotations | indent 4 }}
spec:
{{- if .Values.dash.ingress.tls }}
  tls:
  {{- range .Values.dash.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.dash.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: dashboard-svc-{{ $fullName }}
              servicePort: {{ $.Values.dash.service.port }}
  {{- end }}
{{- end }}
