apiVersion: v1
kind: Service
metadata:
  name: dashboard-svc-{{ include "tyk-pro.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: dashboard-svc-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.dash.service.port }}
    targetPort: {{ .Values.dash.service.port }}
    protocol: TCP
  type: NodePort
  selector:
    app: dashboard-{{ include "tyk-pro.fullname" . }}
    release: {{ .Release.Name }}
