apiVersion: v1
kind: Service
metadata:
  name: gateway-svc-{{ include "tyk-headless.fullname" . }}
  labels:
    app: gateway-svc-{{ include "tyk-headless.fullname" . }}
    chart: {{ include "tyk-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: 443
    targetPort: {{ .Values.gateway.service.port }}
    protocol: TCP
  selector:
    app: gateway-{{ include "tyk-headless.fullname" . }}
    release: {{ .Release.Name }}
{{- if eq .Values.gateway.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.gateway.service.externalTrafficPolicy }}
{{- end }}